In [5]:
import pandas as pd
import numpy as np

In [6]:
original = pd.read_csv("../input/driver_imgs_list.csv")
original.head()

  subject classname            img
0    p002        c0  img_44733.jpg
1    p002        c0  img_72999.jpg
2    p002        c0  img_25094.jpg
3    p002        c0  img_69092.jpg
4    p002        c0  img_92629.jpg

In [7]:
original['processed'] = original['img'].str.replace('.jpg', '_processed.png', regex=False)
original.head()

  subject classname            img                processed
0    p002        c0  img_44733.jpg  img_44733_processed.png
1    p002        c0  img_72999.jpg  img_72999_processed.png
2    p002        c0  img_25094.jpg  img_25094_processed.png
3    p002        c0  img_69092.jpg  img_69092_processed.png
4    p002        c0  img_92629.jpg  img_92629_processed.png

In [8]:
original.to_csv("../input/driver_imgs_list_processed.csv", index=False)